export const FETCH_USER = 'FETCH_USER';
export const FETCH_RECENTLY_PLAYED  = 'FETCH_RECENTLY_PLAYED';
export const FETCH_USER_TOP_TRACKS = 'FETCH_USER_TOP_TRACKS';
export const FETCH_USER_TOP_ARTISTS = 'FETCH_USER_TOP_ARTISTS';

